const servicesData = [
  {
    id: 1,
    name: "Post UTME Registration",
    code: "SRV-001",
    category: "Admission",
    price: 2500,
    orders: 1842,
    status: "Active",
    date: "May 31, 2024",
    time: "10:24 AM",
    color: "#6D5EF9",
    icon: "graduation",
  },
  {
    id: 2,
    name: "JAMB Registration",
    code: "SRV-002",
    category: "JAMB",
    price: 7000,
    orders: 1264,
    status: "Active",
    date: "May 30, 2024",
    time: "09:15 AM",
    color: "#2563EB",
    icon: "jamb",
  },
  {
    id: 3,
    name: "JAMB Change of Institution",
    code: "SRV-003",
    category: "JAMB",
    price: 3500,
    orders: 731,
    status: "Active",
    date: "May 29, 2024",
    time: "01:35 PM",
    color: "#0891B2",
    icon: "school",
  },
  {
    id: 4,
    name: "O'Level Result Upload",
    code: "SRV-004",
    category: "JAMB",
    price: 1500,
    orders: 642,
    status: "Active",
    date: "May 28, 2024",
    time: "08:30 AM",
    color: "#16A34A",
    icon: "certificate",
  },
  {
    id: 5,
    name: "Admission Letter Printing",
    code: "SRV-005",
    category: "Admission",
    price: 1000,
    orders: 589,
    status: "Active",
    date: "May 27, 2024",
    time: "11:10 AM",
    color: "#EC4899",
    icon: "admission",
  },
  {
    id: 6,
    name: "Original Result Printing",
    code: "SRV-006",
    category: "JAMB",
    price: 1200,
    orders: 401,
    status: "Active",
    date: "May 26, 2024",
    time: "03:20 PM",
    color: "#F97316",
    icon: "certificate",
  },
  {
    id: 7,
    name: "Birth Certificate",
    code: "SRV-007",
    category: "Documents",
    price: 3000,
    orders: 350,
    status: "Inactive",
    date: "May 25, 2024",
    time: "09:55 AM",
    color: "#14B8A6",
    icon: "idcard",
  },
  {
    id: 8,
    name: "Affidavit Processing",
    code: "SRV-008",
    category: "Legal",
    price: 2000,
    orders: 228,
    status: "Active",
    date: "May 24, 2024",
    time: "02:40 PM",
    color: "#8B5CF6",
    icon: "affidavit",
  },
  {
    id: 9,
    name: "NYSC Registration",
    code: "SRV-009",
    category: "NYSC",
    price: 1500,
    orders: 305,
    status: "Active",
    date: "May 23, 2024",
    time: "12:10 PM",
    color: "#22C55E",
    icon: "graduation",
  },
  {
    id: 10,
    name: "Transcript Processing",
    code: "SRV-010",
    category: "School",
    price: 5000,
    orders: 172,
    status: "Inactive",
    date: "May 22, 2024",
    time: "04:15 PM",
    color: "#F59E0B",
    icon: "school",
  },
  {
    id: 11,
    name: "Certificate Verification",
    code: "SRV-011",
    category: "Verification",
    price: 2500,
    orders: 118,
    status: "Active",
    date: "May 21, 2024",
    time: "11:30 AM",
    color: "#0EA5E9",
    icon: "certificate",
  },
  {
    id: 12,
    name: "Hostel Allocation",
    code: "SRV-012",
    category: "Accommodation",
    price: 1000,
    orders: 210,
    status: "Active",
    date: "May 20, 2024",
    time: "10:05 AM",
    color: "#E11D48",
    icon: "school",
  },
  {
    id: 13,
    name: "Student ID Card",
    code: "SRV-013",
    category: "Identity",
    price: 800,
    orders: 490,
    status: "Active",
    date: "May 19, 2024",
    time: "09:00 AM",
    color: "#4F46E5",
    icon: "idcard",
  },
  {
    id: 14,
    name: "Online Application",
    code: "SRV-014",
    category: "Portal",
    price: 1800,
    orders: 263,
    status: "Inactive",
    date: "May 18, 2024",
    time: "02:50 PM",
    color: "#059669",
    icon: "web",
  },
  {
    id: 15,
    name: "Acceptance Fee Payment",
    code: "SRV-015",
    category: "Payment",
    price: 500,
    orders: 982,
    status: "Active",
    date: "May 17, 2024",
    time: "08:45 AM",
    color: "#7C3AED",
    icon: "admission",
  },
];

export default servicesData;
