const usersData = [
  {
    id: 1,
    name: "John Doe",
    username: "johndoe",
    email: "john.doe@gmail.com",
    phone: "08012345678",
    role: "Student",
    registered: "May 31, 2024",
    time: "10:24 AM",
    source: "Web",
    status: "Active",
    avatar: "https://i.pravatar.cc/150?img=1",
  },
  {
    id: 2,
    name: "Sarah Johnson",
    username: "sarahjohnson",
    email: "sarah@gmail.com",
    phone: "08087654321",
    role: "Student",
    registered: "May 30, 2024",
    time: "09:12 AM",
    source: "Mobile App",
    status: "Active",
    avatar: "https://i.pravatar.cc/150?img=5",
  },
  {
    id: 3,
    name: "Michael Brown",
    username: "michaelbrown",
    email: "michael@gmail.com",
    phone: "08123456789",
    role: "Administrator",
    registered: "May 29, 2024",
    time: "11:45 AM",
    source: "Admin Portal",
    status: "Suspended",
    avatar: "https://i.pravatar.cc/150?img=12",
  },
  {
    id: 4,
    name: "Jessica Smith",
    username: "jessicasmith",
    email: "jessica@gmail.com",
    phone: "08098765432",
    role: "Staff",
    registered: "May 28, 2024",
    time: "02:14 PM",
    source: "Web",
    status: "Inactive",
    avatar: "https://i.pravatar.cc/150?img=15",
  },
  {
    id: 5,
    name: "David Wilson",
    username: "davidwilson",
    email: "david@gmail.com",
    phone: "08033445566",
    role: "Student",
    registered: "May 27, 2024",
    time: "04:18 PM",
    source: "Web",
    status: "Active",
    avatar: "https://i.pravatar.cc/150?img=8",
  },
  {
    id: 6,
    name: "Grace Williams",
    username: "gracewilliams",
    email: "grace@gmail.com",
    phone: "08044556677",
    role: "Staff",
    registered: "May 26, 2024",
    time: "12:02 PM",
    source: "Mobile App",
    status: "Active",
    avatar: "https://i.pravatar.cc/150?img=20",
  },
  {
    id: 7,
    name: "Daniel Adams",
    username: "danieladams",
    email: "daniel@gmail.com",
    phone: "08111222333",
    role: "Student",
    registered: "May 25, 2024",
    time: "09:47 AM",
    source: "Admin Portal",
    status: "Suspended",
    avatar: "https://i.pravatar.cc/150?img=17",
  },
  {
    id: 8,
    name: "Samuel Jackson",
    username: "samueljackson",
    email: "samuel@gmail.com",
    phone: "08066778899",
    role: "Student",
    registered: "May 24, 2024",
    time: "08:51 AM",
    source: "Web",
    status: "Active",
    avatar: "https://i.pravatar.cc/150?img=23",
  },
  {
    id: 9,
    name: "Mary James",
    username: "maryjames",
    email: "mary@gmail.com",
    phone: "08012344321",
    role: "Student",
    registered: "May 23, 2024",
    time: "03:42 PM",
    source: "Mobile App",
    status: "Inactive",
    avatar: "https://i.pravatar.cc/150?img=25",
  },
  {
    id: 10,
    name: "Victor Peter",
    username: "victorpeter",
    email: "victor@gmail.com",
    phone: "08122334455",
    role: "Administrator",
    registered: "May 22, 2024",
    time: "06:28 PM",
    source: "Admin Portal",
    status: "Active",
    avatar: "https://i.pravatar.cc/150?img=30",
  },
  {
    id: 11,
    name: "Blessing David",
    username: "blessingdavid",
    email: "blessing@gmail.com",
    phone: "08199887766",
    role: "Student",
    registered: "May 21, 2024",
    time: "01:19 PM",
    source: "Web",
    status: "Active",
    avatar: "https://i.pravatar.cc/150?img=32",
  },
  {
    id: 12,
    name: "Richard Sunday",
    username: "richstar",
    email: "richard@gmail.com",
    phone: "09019403762",
    role: "Administrator",
    registered: "May 20, 2024",
    time: "10:33 AM",
    source: "Admin Portal",
    status: "Active",
    avatar: "https://i.pravatar.cc/150?img=35",
  },
  {
    id: 13,
    name: "Sophia Taylor",
    username: "sophiataylor",
    email: "sophia@gmail.com",
    phone: "08134567890",
    role: "Staff",
    registered: "May 19, 2024",
    time: "11:10 AM",
    source: "Web",
    status: "Inactive",
    avatar: "https://i.pravatar.cc/150?img=40",
  },
  {
    id: 14,
    name: "Anthony Evans",
    username: "anthonyevans",
    email: "anthony@gmail.com",
    phone: "08099887766",
    role: "Student",
    registered: "May 18, 2024",
    time: "04:25 PM",
    source: "Mobile App",
    status: "Active",
    avatar: "https://i.pravatar.cc/150?img=45",
  },
  {
    id: 15,
    name: "Linda Green",
    username: "lindagreen",
    email: "linda@gmail.com",
    phone: "08187654321",
    role: "Staff",
    registered: "May 17, 2024",
    time: "07:45 AM",
    source: "Web",
    status: "Suspended",
    avatar: "https://i.pravatar.cc/150?img=48",
  },
  {
    id: 16,
    name: "James Walker",
    username: "jameswalker",
    email: "james@gmail.com",
    phone: "08111112222",
    role: "Student",
    registered: "May 16, 2024",
    time: "03:30 PM",
    source: "Admin Portal",
    status: "Active",
    avatar: "https://i.pravatar.cc/150?img=50",
  },
  {
    id: 17,
    name: "Emily Clark",
    username: "emilyclark",
    email: "emily@gmail.com",
    phone: "08011223344",
    role: "Student",
    registered: "May 15, 2024",
    time: "09:05 AM",
    source: "Mobile App",
    status: "Inactive",
    avatar: "https://i.pravatar.cc/150?img=52",
  },
  {
    id: 18,
    name: "Christopher White",
    username: "christopher",
    email: "chris@gmail.com",
    phone: "08055443322",
    role: "Administrator",
    registered: "May 14, 2024",
    time: "05:18 PM",
    source: "Admin Portal",
    status: "Active",
    avatar: "https://i.pravatar.cc/150?img=56",
  },
  {
    id: 19,
    name: "Olivia Martin",
    username: "oliviamartin",
    email: "olivia@gmail.com",
    phone: "08155667788",
    role: "Student",
    registered: "May 13, 2024",
    time: "02:50 PM",
    source: "Web",
    status: "Suspended",
    avatar: "https://i.pravatar.cc/150?img=58",
  },
  {
    id: 20,
    name: "Benjamin Lewis",
    username: "benjaminlewis",
    email: "ben@gmail.com",
    phone: "08066554433",
    role: "Staff",
    registered: "May 12, 2024",
    time: "08:15 AM",
    source: "Mobile App",
    status: "Active",
    avatar: "https://i.pravatar.cc/150?img=60",
  },
];

export default usersData;