export const AllCourses = {
  "Rivers State University": [
    "Accounting",
    "Adult and Community Education",
    "Agricultural and Environmental Engineering",
    "Agricultural Economics and Extension",
    "Agricultural Engineering",
    "Agricultural Extension and Rural Development",
    "Agricultural Science and Education",
    "Agriculture",
    "Anatomy",
    "Animal and Environmental Biology",
    "Animal Science",
    "Applied Biology",
    "Architecture",
    "Banking and Finance",
    "Biochemistry",
    "Biology",
    "Business Education",
    "Business Management",
    "Chemical and Petrochemical Engineering",
    "Chemistry",
    "Civil Engineering",
    "Computer Engineering",
    "Computer Science",
    "Criminology and Penology",
    "Crop Science",
    "Economics",
    "Education and Biology",
    "Education and Chemistry",
    "Education and Mathematics",
    "Education and Physics",
    "Education and Science",
    "Educational Administration and Planning",
    "Educational Management",
    "Electrical and Electronic Engineering",
    "English and Literary Studies",
    "Environmental Management",
    "Estate Management",
    "Fisheries and Aquatic Environment",
    "Food Science and Technology",
    "Forestry and Environment",
    "Geography and Environmental Management",
    "Geology",
    "History and Diplomatic Studies",
    "Home Science and Management",
    "Land Surveying and Geomatics",
    "Law",
    "Library and Information Science",
    "Literature in English",
    "Marine Engineering",
    "Maritime Science",
    "Marketing",
    "Mass Communication",
    "Mathematics",
    "Mechanical Engineering",
    "Medical Laboratory Science",
    "Medicine and Surgery",
    "Microbiology",
    "Nursing Science",
    "Office and Information Management",
    "Petroleum Engineering",
    "Philosophy",
    "Physics",
    "Plant Science and Biotechnology",
    "Political Science",
    "Psychology",
    "Public Relations and Advertising",
    "Quantity Surveying",
    "Religious and Cultural Studies",
    "Sociology",
    "Surveying and Geomatics",
    "Theatre Arts",
    "Urban and Regional Planning",
  ],
  "Abia State University": [
    "Accounting",
    "Agric-Economics and Extension",
    "Agricultural Science and Education",
    "Anatomy",
    "Animal Science and Fisheries",
    "Architecture",
    "Banking and Finance",
    "Biochemistry",
    "Botany",
    "Building Technology",
    "Business Administration",
    "Business Education",
    "Chemistry and Industrial Chemistry",
    "Civil Engineering",
    "Computer Engineering",
    "Computer Engineering Technology",
    "Computer Science",
    "Crop Production and Protection",
    "Economics",
    "Education and Accounting",
    "Education and Agricultural Science",
    "Education and Biology",
    "Education and Chemistry",
    "Education and Government",
    "Education and Integrated Science",
    "Education and Mathematics",
    "Education and Physics",
    "Education and Political Science",
    "Education and Social Studies",
    "Education/Fine Art",
    "Educational Management and Planning",
    "Electrical/Electronics Engineering",
    "English Language and Literature",
    "Environmental Resources Management",
    "Environmental Science",
    "Estate Management",
    "Fine/Applied Arts",
    "Food Science and Technology",
    "French",
    "Geography",
    "Geography and Planning",
    "Government and Public Administration",
    "History and International Studies",
    "Home Economics and Education",
    "Igbo",
    "Information and Communication Technology",
    "Language and Literature",
    "Law",
    "Library and Information Science",
    "Library Science",
    "Linguistics and Communication Studies",
    "Management",
    "Marketing",
    "Mass Communication",
    "Mathematics",
    "Medicine and Surgery",
    "Microbiology",
    "Nursing Science",
    "Optometry",
    "Pharmacy",
    "Physiology",
    "Plant Science and Biotechnology",
    "Political Science",
    "Public Health",
    "Pure and Industrial Physics",
    "Religious Studies",
    "Sociology",
    "Soil Science",
    "Statistics",
    "Surveying and Geo-Informatics",
    "Urban and Regional Planning",
    "Zoology",
  ],
  "Abubakar Tafawa Balewa University": [
    "Agric-Economics and Extension",
    "Agricultural Engineering",
    "Agricultural Science and Education",
    "Agriculture",
    "Animal Production",
    "Applied Botany",
    "Applied Ecology",
    "Applied Geology",
    "Applied Zoology",
    "Architecture",
    "Automobile Engineering",
    "Automobile Technology Education",
    "Banking and Finance",
    "Biochemistry",
    "Building Education",
    "Building Technology",
    "Business Education",
    "Chemical Engineering",
    "Chemistry",
    "Civil Engineering",
    "Computer and Communication Engineering",
    "Computer Science",
    "Crop Production",
    "Ecology",
    "Education and Biology",
    "Education and Chemistry",
    "Education and Computer Science",
    "Education and Integrated Science",
    "Education and Mathematics",
    "Education and Physics",
    "Education and Science",
    "Electrical and Electronics Engineering",
    "Electrical/Electronics Education",
    "Environmental Management Technology",
    "Estate Management",
    "Geophysics",
    "Industrial Chemistry",
    "Industrial Design",
    "Information Technology",
    "Library and Information Science",
    "Management Technology",
    "Mathematics",
    "Mechanical Engineering",
    "Mechatronics and Systems Engineering",
    "Medicine and Surgery",
    "Microbiology",
    "Petroleum Engineering",
    "Physics and Applied Physics",
    "Quantity Surveying",
    "Secretarial Education",
    "Statistics",
    "Surveying and Geo-Informatics",
    "Urban and Regional Planning",
  ],
  "Adamawa State University": [
    "Accounting",
    "Agricultural Economics and Extension",
    "Agriculture",
    "Animal Production",
    "Banking and Finance",
    "Biochemistry",
    "Biological Science",
    "Biotechnology",
    "Botany",
    "Business Administration",
    "Business Education",
    "Chemistry",
    "Computer Science",
    "Crop Production",
    "Economics",
    "Education and Biology",
    "Education and Chemistry",
    "Education and Computer Science",
    "Education and Economics",
    "Education and English Language",
    "Education and Geography",
    "Education and Mathematics",
    "Education and Physics",
    "Education and Political Science",
    "Education and Science",
    "English Language",
    "Fisheries and Aquaculture",
    "Forestry and Wildlife Management",
    "Geography",
    "Geology",
    "Guidance and Counselling",
    "History",
    "Industrial Chemistry",
    "Law",
    "Library and Information Science",
    "Linguistics",
    "Management Information System",
    "Mass Communication",
    "Mathematics",
    "Microbiology",
    "Physics",
    "Political Science",
    "Primary Education Studies",
    "Public Administration",
    "Pure Chemistry",
    "Sociology",
    "Statistics",
    "Zoology",
  ],
  "Adekunle Ajasin University": [
    "Accounting",
    "Adult Education",
    "Agriculture",
    "Architecture",
    "Banking and Finance",
    "Biochemistry",
    "Biology",
    "Business Administration",
    "Chemistry",
    "Computer Science",
    "Criminology and Security Studies",
    "Economics",
    "Education and Accounting",
    "Education and Biology",
    "Education and Chemistry",
    "Education and Computer Science",
    "Education and Economics",
    "Education and English Language",
    "Education and Geography",
    "Education and History",
    "Education and Integrated Science",
    "Education and Mathematics",
    "Education and Physics",
    "Education and Political Science",
    "Education and Religious Studies",
    "Educational Management",
    "English Studies",
    "Environmental Biology and Fisheries",
    "Estate Management",
    "Geography and Planning Science",
    "Geology",
    "Guidance and Counselling",
    "History and International Studies",
    "Human Kinetics",
    "Industrial Chemistry",
    "Law",
    "Linguistics",
    "Mass Communication",
    "Mathematics",
    "Microbiology",
    "Philosophy",
    "Physics",
    "Plant Science and Biotechnology",
    "Political Science",
    "Psychology",
    "Public Administration",
    "Religious Studies",
    "Sociology",
    "Statistics",
    "Surveying and Geo-Informatics",
    "Urban and Regional Planning",
  ],
  "Ahmadu Bello University": [
    "Accounting",
    "Actuarial Science",
    "Adult Education",
    "Agricultural Economics and Rural Sociology",
    "Agricultural Engineering",
    "Agriculture",
    "Anatomy",
    "Animal Science",
    "Arabic Studies",
    "Architecture",
    "Banking and Finance",
    "Biochemistry",
    "Biological Science",
    "Botany",
    "Building",
    "Business Administration",
    "Chemical Engineering",
    "Chemistry",
    "Civil Engineering",
    "Computer Engineering",
    "Computer Science",
    "Dentistry and Dental Surgery",
    "Doctor of Pharmacy",
    "Economics",
    "Education and Arabic",
    "Education and Biology",
    "Education and Chemistry",
    "Education and Christian Religious Studies",
    "Education and Computer Science",
    "Education and Economics",
    "Education and English Language",
    "Education and Geography",
    "Education and Hausa",
    "Education and History",
    "Education and Integrated Science",
    "Education and Islamic Studies",
    "Education and Mathematics",
    "Education and Physics",
    "Education and Social Studies",
    "Educational Administration and Planning",
    "Electrical Engineering",
    "English Language",
    "Estate Management",
    "Fine Arts",
    "Forestry and Wildlife Management",
    "French",
    "Geography",
    "Geology",
    "Glass Technology",
    "Guidance and Counselling",
    "Hausa",
    "History",
    "Home Economics",
    "Human Physiology",
    "Industrial Design",
    "Insurance",
    "International Studies",
    "Islamic Studies",
    "Law",
    "Library and Information Science",
    "Linguistics",
    "Literature in English",
    "Local Government and Development Studies",
    "Mass Communication",
    "Mathematics",
    "Mechanical Engineering",
    "Medical Laboratory Science",
    "Medicine and Surgery",
    "Metallurgical Engineering",
    "Microbiology",
    "Mining Engineering",
    "Nursing Science",
    "Petroleum Engineering",
    "Pharmacy",
    "Physical and Health Education",
    "Physics",
    "Physiology",
    "Political Science",
    "Polymer and Textile Engineering",
    "Private and Islamic Law",
    "Public Administration",
    "Quantity Surveying",
    "Radiography",
    "Sociology",
    "Soil Science",
    "Statistics",
    "Surveying and Geo-Informatics",
    "Theatre and Performing Arts",
    "Urban and Regional Planning",
    "Veterinary Medicine",
    "Zoology",
  ],
  "Air Force Institute of Technology": [
    "Accounting",
    "Aerospace Engineering",
    "Automotive Engineering",
    "Banking and Finance",
    "Business Administration",
    "Chemistry",
    "Civil Engineering",
    "Computer Science",
    "Cyber Security",
    "Economics",
    "Electrical and Electronics Engineering",
    "Information and Communication Technology",
    "International Relations",
    "Marketing",
    "Mathematics",
    "Mechanical Engineering",
    "Metallurgical and Material Engineering",
    "Physics",
    "Physics with Electronics",
    "Statistics",
  ],
  "Akwa Ibom State University": [
  "Accounting",
  "Agricultural Economics and Extension",
  "Animal Science",
  "Applied Geophysics",
  "Biochemistry",
  "Biological Sciences",
  "Botany",
  "Business Administration",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Computer Science",
  "Crop Science",
  "Economics",
  "Education and Biology",
  "Education and Chemistry",
  "Education and Computer Science",
  "Education and Integrated Science",
  "Education and Mathematics",
  "Education and Physics",
  "Electrical and Electronics Engineering",
  "English and Literary Studies",
  "Fisheries and Aquaculture",
  "Genetics and Biotechnology",
  "Geology",
  "History and International Studies",
  "Information and Communication Technology",
  "Marine Biology",
  "Marine Engineering",
  "Marketing",
  "Mass Communication",
  "Mathematics",
  "Mechanical Engineering",
  "Microbiology",
  "Performing Arts",
  "Petroleum Engineering",
  "Philosophy",
  "Physics",
  "Political Science",
  "Public Administration",
  "Religious Studies",
  "Sociology",
  "Statistics",
  "Zoology"
],
"Alex Ekwueme Federal University Ndufu-Alike": [
  "Accounting",
  "Agribusiness and Management",
  "Agricultural Economics",
  "Agriculture",
  "Anatomy",
  "Applied Geophysics",
  "Architecture",
  "Banking and Finance",
  "Biochemistry",
  "Biology",
  "Biotechnology",
  "Business Administration",
  "Business Education",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Computer Science",
  "Criminology and Security Studies",
  "Economics",
  "Education and Biology",
  "Education and Chemistry",
  "Education and Mathematics",
  "Education and Physics",
  "Electrical/Electronics Engineering",
  "English and Literary Studies",
  "Entrepreneurship",
  "Environmental Management and Toxicology",
  "Fine and Applied Arts",
  "Fisheries and Aquaculture",
  "French",
  "Geography",
  "Geology",
  "Guidance and Counselling",
  "History and Strategic Studies",
  "Human Nutrition and Dietetics",
  "Law",
  "Library and Information Science",
  "Linguistics",
  "Mass Communication",
  "Mathematics",
  "Mechanical Engineering",
  "Medical Laboratory Science",
  "Medicine and Surgery",
  "Microbiology",
  "Nursing Science",
  "Philosophy",
  "Physics",
  "Physiology",
  "Political Science",
  "Psychology",
  "Public Administration",
  "Religious Studies",
  "Sociology",
  "Soil Science",
  "Statistics",
  "Theatre Arts",
  "Urban and Regional Planning"
],
"Ambrose Alli University": [
  "Accounting",
  "Agricultural Economics and Extension",
  "Agricultural Science and Education",
  "Agriculture",
  "Anatomy",
  "Animal Science",
  "Applied Physics",
  "Architecture",
  "Banking and Finance",
  "Biochemistry",
  "Botany",
  "Building",
  "Business Administration",
  "Business Education",
  "Chemistry",
  "Civil Engineering",
  "Computer Science",
  "Curriculum and Instruction",
  "Economics",
  "Education and Biology",
  "Education and Chemistry",
  "Education and Economics",
  "Education and English Language",
  "Education and Geography",
  "Education and History",
  "Education and Mathematics",
  "Education and Physics",
  "Education and Political Science",
  "Education and Religious Studies",
  "Educational Management",
  "Electrical/Electronics Engineering",
  "English Language",
  "English Literature",
  "Estate Management",
  "Fine and Applied Arts",
  "Geography and Environmental Management",
  "Geophysics",
  "Guidance and Counselling",
  "History and International Studies",
  "Home Economics and Education",
  "Human Nutrition and Dietetics",
  "Industrial and Production Engineering",
  "Industrial Chemistry",
  "Industrial Mathematics",
  "Law",
  "Library and Information Science",
  "Mass Communication",
  "Mathematics",
  "Mechanical Engineering",
  "Medical Laboratory Science",
  "Medicine and Surgery",
  "Microbiology",
  "Nursing Science",
  "Philosophy",
  "Physical and Health Education",
  "Physics",
  "Physiology",
  "Political Science",
  "Public Administration",
  "Religious Management and Cultural Studies",
  "Sociology",
  "Soil Science",
  "Statistics",
  "Theatre and Media Arts",
  "Vocational and Technical Education",
  "Zoology"
],
"Bauchi State University": [
  "Accounting",
  "Agricultural Economics and Extension",
  "Agriculture",
  "Animal Production",
  "Arabic",
  "Banking and Finance",
  "Biochemistry",
  "Biological Sciences",
  "Botany",
  "Business Administration",
  "Chemistry",
  "Computer Science",
  "Economics",
  "Education and Biology",
  "Education and Chemistry",
  "Education and Computer Science",
  "Education and English Language",
  "Education and Mathematics",
  "Education and Physics",
  "Education and Political Science",
  "Education and Sociology",
  "English Language",
  "Environmental Health Science",
  "Geography",
  "Hausa",
  "Human Anatomy",
  "Human Physiology",
  "Law",
  "Library and Information Science",
  "Literature in English",
  "Mass Communication",
  "Mathematics",
  "Microbiology",
  "Nursing Science",
  "Pharmacology",
  "Physics",
  "Political Science",
  "Public Administration",
  "Public Health",
  "Sociology",
  "Statistics",
  "Taxation",
  "Zoology"
],
"Bayero University": [
  "Accounting",
  "Adult Education",
  "Agriculture",
  "Anatomy",
  "Applied Biology",
  "Arabic Studies",
  "Architecture",
  "Banking and Finance",
  "Biochemistry",
  "Botany",
  "Business Administration",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Common and Islamic Law",
  "Computer Engineering",
  "Computer Science",
  "Criminology",
  "Dentistry and Dental Surgery",
  "Economics",
  "Education and Arabic",
  "Education and Biology",
  "Education and Chemistry",
  "Education and Economics",
  "Education and English Language",
  "Education and French",
  "Education and Geography",
  "Education and Hausa",
  "Education and History",
  "Education and Islamic Studies",
  "Education and Mathematics",
  "Education and Physics",
  "Electrical Engineering",
  "English Language",
  "Entrepreneurship",
  "Environmental Health Science",
  "Estate Management",
  "Fisheries and Aquaculture",
  "Food Science and Technology",
  "Forestry and Wildlife Management",
  "French",
  "Geography",
  "Geology",
  "Hausa",
  "History",
  "Industrial Chemistry",
  "Information Science and Media Studies",
  "International Relations",
  "Islamic Studies",
  "Law",
  "Library and Information Science",
  "Linguistics",
  "Mass Communication",
  "Mathematics",
  "Mechanical Engineering",
  "Medical Laboratory Science",
  "Medicine and Surgery",
  "Microbiology",
  "Nursing Science",
  "Nutrition and Dietetics",
  "Optometry",
  "Petroleum Engineering",
  "Pharmacy",
  "Physical and Health Education",
  "Physics",
  "Physiology",
  "Political Science",
  "Public Administration",
  "Quantity Surveying",
  "Radiography",
  "Sharia",
  "Sociology",
  "Software Engineering",
  "Special Education",
  "Statistics",
  "Taxation",
  "Theatre and Performing Arts",
  "Urban and Regional Planning",
  "Veterinary Medicine",
  "Zoology"
],
"Bayelsa Medical University": [
  "Anatomy",
  "Biochemistry",
  "Dentistry and Dental Surgery",
  "Doctor of Pharmacy",
  "Environmental Health Science",
  "Human Nutrition and Dietetics",
  "Medical Laboratory Science",
  "Medicine and Surgery",
  "Microbiology",
  "Nursing Science",
  "Optometry",
  "Physiology",
  "Physiotherapy",
  "Public Health",
  "Radiography and Radiation Science"
],
"Benue State University": [
  "Accounting",
  "Anatomy",
  "Biochemistry",
  "Biological Sciences",
  "Business Administration",
  "Chemistry",
  "Computer Science",
  "Economics",
  "Education and Biology",
  "Education and Chemistry",
  "Education and English Language",
  "Education and Integrated Science",
  "Education and Mathematics",
  "Education and Physics",
  "Educational Management",
  "English Language",
  "French",
  "Geography",
  "History",
  "Human Physiology",
  "Industrial Chemistry",
  "Law",
  "Library and Information Science",
  "Mass Communication",
  "Mathematics",
  "Medicine and Surgery",
  "Microbiology",
  "Nursing Science",
  "Physics",
  "Political Science",
  "Pre-Primary and Primary Education",
  "Public Administration",
  "Religious Studies",
  "Sociology",
  "Statistics",
  "Theatre Arts",
  "Urban and Regional Planning"
],
"Borno State University": [
  "Accounting",
  "Agricultural Economics",
  "Agriculture",
  "Animal and Environmental Biology",
  "Arabic Studies",
  "Biochemistry",
  "Business Administration",
  "Chemistry",
  "Computer Science",
  "Criminology and Security Studies",
  "Economics",
  "Education and Biology",
  "Education and Chemistry",
  "Education and Computer Science",
  "Education and English Language",
  "Education and Mathematics",
  "Education and Physics",
  "Educational Management",
  "English Language",
  "Geography",
  "Guidance and Counselling",
  "Hausa",
  "History",
  "Industrial Chemistry",
  "Islamic Studies",
  "Law",
  "Library and Information Science",
  "Mass Communication",
  "Mathematics",
  "Microbiology",
  "Peace Studies and Conflict Resolution",
  "Physics",
  "Plant Science and Biotechnology",
  "Political Science",
  "Public Administration",
  "Public Health",
  "Sharia Law",
  "Sociology",
  "Statistics"
],
"Chukwuemeka Odumegwu Ojukwu University": [
  "Accounting",
  "Agricultural Economics and Extension",
  "Agriculture",
  "Anatomy",
  "Animal Science",
  "Architecture",
  "Banking and Finance",
  "Biochemistry",
  "Biological Sciences",
  "Business Administration",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Computer Science",
  "Criminology and Security Studies",
  "Economics",
  "Education and Biology",
  "Education and Chemistry",
  "Education and Computer Science",
  "Education and Economics",
  "Education and English Language",
  "Education and Igbo",
  "Education and Mathematics",
  "Education and Physics",
  "Educational Management",
  "Electrical/Electronics Engineering",
  "English Language",
  "Entrepreneurship",
  "Environmental Management Technology",
  "Estate Management",
  "Fine and Applied Arts",
  "Food Science and Technology",
  "Forestry and Wildlife",
  "Geography",
  "Geology",
  "History and International Studies",
  "Human Anatomy",
  "Human Physiology",
  "Industrial Physics",
  "Law",
  "Library and Information Science",
  "Linguistics",
  "Marketing",
  "Mass Communication",
  "Mathematics",
  "Mechanical Engineering",
  "Medical Laboratory Science",
  "Medicine and Surgery",
  "Microbiology",
  "Nursing Science",
  "Pharmacy",
  "Philosophy",
  "Physics",
  "Political Science",
  "Primary and Elementary Education",
  "Public Administration",
  "Religious Studies",
  "Sociology",
  "Soil Science",
  "Statistics",
  "Theatre Arts",
  "Urban and Regional Planning"
],
"Delta State University": [
  "Accounting",
  "Adult Education",
  "Agricultural Economics",
  "Agricultural Science and Education",
  "Agriculture",
  "Anatomy",
  "Animal Science",
  "Banking and Finance",
  "Biochemistry",
  "Botany",
  "Business Administration",
  "Business Education",
  "Chemistry",
  "Civil Engineering",
  "Computer Science",
  "Economics",
  "Education and Biology",
  "Education and Chemistry",
  "Education and Economics",
  "Education and English Language",
  "Education and Geography",
  "Education and History",
  "Education and Integrated Science",
  "Education and Mathematics",
  "Education and Physics",
  "Educational Administration",
  "Electrical/Electronics Engineering",
  "English and Literary Studies",
  "Fine and Applied Arts",
  "Fisheries",
  "Forestry and Wildlife",
  "French",
  "Geography and Regional Planning",
  "Geology",
  "Guidance and Counselling",
  "History and International Studies",
  "Home Economics",
  "Human Anatomy",
  "Human Kinetics and Health Education",
  "Industrial Chemistry",
  "Law",
  "Library and Information Science",
  "Linguistics",
  "Mass Communication",
  "Mathematics",
  "Mechanical Engineering",
  "Medical Biochemistry",
  "Medical Laboratory Science",
  "Medicine and Surgery",
  "Microbiology",
  "Music",
  "Nursing Science",
  "Pharmacology",
  "Pharmacy",
  "Philosophy",
  "Physics",
  "Physiology",
  "Political Science",
  "Psychology",
  "Public Administration",
  "Religious Studies",
  "Sociology",
  "Soil Science",
  "Statistics",
  "Theatre Arts",
  "Zoology"
],
};
