const applicationsData = [
  {
    id: 1,
    applicantName: "John Doe",
    email: "john.doe@gmail.com",
    phone: "08012345678",
    service: "Post UTME Registration",
    school: "University of Lagos",
    reference: "PUTME-1001",
    amount: 2500,
    status: "Pending",
    submittedDate: "2026-06-12",
  },

  {
    id: 2,
    applicantName: "Sarah Johnson",
    email: "sarah@gmail.com",
    phone: "08087654321",
    service: "JAMB Registration",
    school: "University of Port Harcourt",
    reference: "JAMB-1002",
    amount: 4500,
    status: "Approved",
    submittedDate: "2026-06-11",
  },

  {
    id: 3,
    applicantName: "Michael Brown",
    email: "michael@gmail.com",
    phone: "08123456789",
    service: "Admission Processing",
    school: "Rivers State University",
    reference: "ADM-1003",
    amount: 10000,
    status: "Processing",
    submittedDate: "2026-06-10",
  },

  {
    id: 4,
    applicantName: "David Wilson",
    email: "david@gmail.com",
    phone: "08033445566",
    service: "School Fees Payment",
    school: "Ignatius Ajuru University",
    reference: "SFP-1004",
    amount: 55000,
    status: "Approved",
    submittedDate: "2026-06-09",
  },

  {
    id: 5,
    applicantName: "Jessica Smith",
    email: "jessica@gmail.com",
    phone: "08098765432",
    service: "Transcript Processing",
    school: "Federal University Otuoke",
    reference: "TRN-1005",
    amount: 15000,
    status: "Rejected",
    submittedDate: "2026-06-08",
  },

  {
    id: 6,
    applicantName: "Daniel Adams",
    email: "daniel@gmail.com",
    phone: "08111222333",
    service: "Post UTME Registration",
    school: "University of Lagos",
    reference: "PUTME-1006",
    amount: 2500,
    status: "Pending",
    submittedDate: "2026-06-07",
  },

  {
    id: 7,
    applicantName: "Grace Williams",
    email: "grace@gmail.com",
    phone: "08044556677",
    service: "Admission Processing",
    school: "University of Port Harcourt",
    reference: "ADM-1007",
    amount: 12000,
    status: "Approved",
    submittedDate: "2026-06-06",
  },

  {
    id: 8,
    applicantName: "Samuel Jackson",
    email: "samuel@gmail.com",
    phone: "08066778899",
    service: "JAMB Registration",
    school: "Rivers State University",
    reference: "JAMB-1008",
    amount: 4500,
    status: "Processing",
    submittedDate: "2026-06-05",
  },

  {
    id: 9,
    applicantName: "Mary James",
    email: "mary@gmail.com",
    phone: "08012344321",
    service: "School Fees Payment",
    school: "University of Lagos",
    reference: "SFP-1009",
    amount: 70000,
    status: "Approved",
    submittedDate: "2026-06-04",
  },

  {
    id: 10,
    applicantName: "Victor Peter",
    email: "victor@gmail.com",
    phone: "08122334455",
    service: "Transcript Processing",
    school: "Ignatius Ajuru University",
    reference: "TRN-1010",
    amount: 18000,
    status: "Pending",
    submittedDate: "2026-06-03",
  },

  {
    id: 11,
    applicantName: "Blessing David",
    email: "blessing@gmail.com",
    phone: "08199887766",
    service: "Post UTME Registration",
    school: "Federal University Otuoke",
    reference: "PUTME-1011",
    amount: 2500,
    status: "Approved",
    submittedDate: "2026-06-02",
  },

  {
    id: 12,
    applicantName: "Richard Sunday",
    email: "richard@gmail.com",
    phone: "09019403762",
    service: "Admission Processing",
    school: "University of Port Harcourt",
    reference: "ADM-1012",
    amount: 15000,
    status: "Processing",
    submittedDate: "2026-06-01",
  },
];

export default applicationsData;